ResumeProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resume/',include('resume.urls'))
]

resume/urls.py
from django.urls import path
from . import views
app_name = 'resume'

urlpatterns = [
    path('home/', views.home,name="home"),
    path('register/', views.register_user, name = 'register_user'),
    path('login/', views.login_user, name = 'login_user'),
    path('logout/',views.logout_user, name = 'logout_user'),
    path('userdetails/',views.userdetails, name = 'userdetails'),
    path('personalinformation/',views.personalinformation, name = 'personalinformation'),
    path('education/',views.education, name = 'education'),
    path('job/',views.job, name = 'job'),
    path('project/',views.project, name = 'project'),
    path('skill/',views.skill, name = 'skill'),
    path('language/',views.language, name = 'language'),
    path('reference/',views.reference, name = 'reference'),
    path('displayinformation/',views.displayinformation,name='displayinformation'),
    path('downloadinpdf/',views.downloadinpdf,name='downloadinpdf'),
    path('under_20/',views.under_20,name='under_20'),
    path('language_address_filter/',views.language_address_filter,name='language_address_filter'),





    


]

resume/models.py
from django.db import models
from django.db.models import Count
from .enums import GENDER_CHOICES, EDUCATION_DEGREE
from dateutil.relativedelta import relativedelta

from datetime import timedelta, datetime
from django.utils import timezone


# Create your models here.

class CustomUser(models.Model):
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    gender = models.CharField(max_length=1,choices=GENDER_CHOICES, default='M')
    phone = models.IntegerField(unique = True)
    date_of_birth = models.DateField("Enter date of birth: ",null= True, blank=True )
    email = models.EmailField("Please enter unique email: ")
    profile_picture = models.ImageField(null=True, upload_to='static/', blank=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    confirm_password = models.CharField(max_length=50)

    @property
    def get_age(self):
        # today1 = datetime.date.today()
        today = timezone.now().date()
        age=relativedelta(today,self.date_of_birth).years
        # point_twenty_ago = today - timedelta(days=365*20)

        # age = CustomUser.objects.filter(date_of_birth__gt=point_twenty_ago)
        return age


        
    
    def __str__(self):
        return f"{self.full_name}"
   
    
class PersonalInformation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, related_name='informations')
    # url to profile
    linkedin = models.URLField()
    github = models.URLField()
    #resume objective
    summary = models.TextField()

class Education(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, related_name='educations')
    title = models.CharField(choices=EDUCATION_DEGREE, max_length=8)
    faculty = models.CharField(max_length=50)
    institution_name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField(blank=True)
    score =models.FloatField()

class Job(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='jobs')
    title = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    company = models.CharField(max_length=50)
    startdate = models.DateField()
    enddate = models.DateField()

class Project(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, related_name="projects")
    title = models.CharField(max_length=50)
    description = models.TextField()

class Skill(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="skills")
    skill = models.CharField(max_length=25)

class Language(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="languages")
    language = models.CharField(max_length=20)

class Reference(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="references")
    reference = models.CharField(max_length=100)

 

resume/forms.py
from django import forms
from .models import CustomUser, PersonalInformation, Education, Job, Project, Skill, Language, Reference


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        # password = forms.CharField(widget=forms.PasswordInput)
        # confirm_password = forms.CharField(widget=forms.PasswordInput)
        # widgets = {
        #    'password': forms.PasswordInput(),
        #    'confirm_password': forms.PasswordInput(),
        # }

        fields = ['full_name','address','gender','phone','date_of_birth','email','profile_picture']

class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        password = forms.CharField(widget=forms.PasswordInput)
        confirm_password = forms.CharField(widget=forms.PasswordInput)

        fields =['username','phone','password','confirm_password']



class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)


class PersonalInformationForm(forms.ModelForm):
    class Meta:
        model = PersonalInformation
        fields = ['linkedin','github','summary']


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = '__all__'
        ### not displaying the user field in each form
        widgets = {
            'user': forms.HiddenInput(),
        }

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }

class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }

class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }

resume/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse
import requests
from xhtml2pdf import pisa

### library for template loading
from django.template.loader import get_template 
from django.template import Context 

from django.http import HttpResponse
from .models import CustomUser,PersonalInformation, Education, Project, Job, Reference, Language, Skill

##working with django forms
from .forms import CustomUserForm,LoginForm, RegisterForm, EducationForm, JobForm, SkillForm, ReferenceForm, LanguageForm,ProjectForm, PersonalInformationForm

## register
def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            # Process the form data and save the user
            form.save()
            return redirect('resume:login_user')
            # Redirect to a success page or login page
            # For example: return redirect('resume:login_user')
    else:
        form = RegisterForm()

    return render(request, 'register.html',{'form':form})

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # username = form.cleaned_data['username']
            # password = form.cleaned_data['password']
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = CustomUser.objects.filter(username=username, password=password)
            user_id = user.values('id')
            if user.exists():
                user = user.first()
                request.session['user_id'] = user.id
                return redirect(reverse('resume:home'))
            else:
                return HttpResponse("Invalid Username or password.")
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})



def logout_user(request):
    request.session.pop('user_id',None)
    return redirect(reverse('resume:login_user'))

### home function in general
# def home(request):
#     user_id = request.session.get('user_id')

#     if user_id:    
#         user = CustomUser.objects.filter(id = user_id).first()
#         context = {
#             'user':user,
#         }
#         return render(request,'index.html',context)
#     else:
#         return redirect(reverse('resume:login_user'))
    













### added upto here

# # Create your views here.
# def register_user(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         phone = request.POST['phone']
#         password = request.POST['password']
#         confirm_password = request.POST['confirm_password']
        
#         if not(username and phone and password and confirm_password):
#             print("Please fill up the required details!!")
#         elif password != confirm_password:
#             print("Passwords didnt match!! Please try again.")
#         else:
#             CustomUser.objects.create(username = username, phone = phone, password = password)
#             # user = CustomUser(username = username, phone = phone, password = password)
#             # user.save()
#             return redirect(reverse('resume:login_user'))
#     return render(request,'register.html')

# def login_user(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         ## user filter with exists instead of get with DoesNotExists
#         user= CustomUser.objects.filter(username=username, password=password)
#         user_id = user.values('id')

#         if user.exists():
#             user = user.first()
#             request.session['user_id'] = user.id
#             return redirect(reverse('resume:indexpage'))       
#         else:
#             return HttpResponse("Invalid Username or password.")       
#     return render(request,'login.html')



# def login_user(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         try:
#             user = User.objects.get(username=username, password=password)
#         except User.DoesNotExist:
#             user = None

#         if user is not None:
#             return redirect(reverse('resume:indexpage'))
#         else:
#             return HttpResponse("Invalid Username or password.")

#     return render(request, 'login.html')


# def logout_user(request):
#     request.session.pop('user_id',None)
#     return redirect(reverse('resume:login_user'))

# def indexpage(request):
#     user_id = request.session.get('user_id')

#     if user_id:    
#         user = CustomUser.objects.filter(id = user_id).first()
#         context = {
#             'user':user,
#         }
#         return render(request,'index.html',context)
#     else:
#         return redirect(reverse('resume:login_user'))
    

# # View function for CustomUser (User Details)
# def user_details(request):
#     if request.method == 'POST':
#         form = CustomUserForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse('user_details'))
#     else:
#         form = CustomUserForm()
#     users = CustomUser.objects.all()
#     context = {
#         'form': form,
#         'users': users,
#     }
#     return render(request, 'user_details.html', context)

#view function for general details

'''
## needs some logic for customization
def userdetails(request):
    print(77777777777777777,request.FILES.get('profile_picture'))
    user_id = request.session.get('user_id')
    if user_id:
        user = CustomUser.objects.filter(id=user_id).first()
        if user:
            # user_details = user

            user_details,created= CustomUser.objects.get_or_create(id = user_id)
            form = CustomUserForm(instance=user_details)
            if request.method == 'POST':
                if 'Save' in request.POST:
                    form = CustomUserForm(request.POST, instance=user_details)
                    if form.is_valid():
                        form.save()
                        return redirect(reverse('resume:userdetails'))
 
                
            else:
                form = CustomUserForm(instance=user_details)
            context = {
                'form': form,
                'user_details':user_details,
            }
            return render(request, 'userdetails.html', context)
    else:
        return redirect(reverse('resume:login_user'))'''



def userdetails(request):
    user_id = request.session.get('user_id')
    if user_id:
        user = CustomUser.objects.filter(id=user_id).first()
        if user:
            user_details, created = CustomUser.objects.get_or_create(id=user_id)
            if request.method == 'POST':
                form = CustomUserForm(request.POST, request.FILES, instance=user_details)
                if form.is_valid():
                    form.save()
                    return redirect(reverse('resume:userdetails'))
                else:
                    print(form.errors)
            else:
                form = CustomUserForm(instance=user_details)
            context = {
                'form': form,
                'user_details': user_details,
            }
            return render(request, 'userdetails.html', context)
    else:
        return redirect(reverse('resume:login_user'))











        
# View function for Personal Information
def personalinformation(request):
    user_id = request.session.get('user_id')
    if user_id:
        user = CustomUser.objects.filter(id=user_id).first()
        if user:
            personal_info, created = PersonalInformation.objects.get_or_create(user=user)
            form = PersonalInformationForm(instance=personal_info)
            if request.method == 'POST':
                if 'Save' in request.POST:
                # Create or Update operation
                    form = PersonalInformationForm(request.POST, instance=personal_info)
                    if form.is_valid():
                        form.save()
                        return redirect(reverse('resume:personalinformation'))
                elif 'Delete' in request.POST:
                    personal_info.delete()
                    return redirect(reverse('resume:personalinformation'))
            else:
                form = PersonalInformationForm(instance=personal_info)
            context = {
                'form': form,
                'personal_info': personal_info,
            }
            return render(request, 'generalinformation.html', context)
        else:
            return HttpResponse("User not found.")
    else:
        return redirect(reverse('resume:login_user'))



### works well with adding and deleting information regarding education
def education(request):
    user_id = request.session.get('user_id')
    if user_id:
        user = CustomUser.objects.filter(id=user_id).first()
        if user:
            education_info = Education.objects.filter(user=user)
            if request.method == 'POST':
                if 'delete' in request.POST:
                    education_id = int(request.POST.get('delete'))
                    education = get_object_or_404(Education, id=education_id, user=user)
                    print(education_id,7777777)
                    education.delete()
                    return redirect(reverse('resume:education'))

                # For other form submissions (Add and Save), we'll handle form validation
                form = EducationForm(request.POST)
                if form.is_valid():
                    new_education = form.save(commit=False)
                    new_education.user = user
                    new_education.save()
                    return redirect(reverse('resume:education'))
            else:
                form = EducationForm(initial={'user': user})

resume/templates/education.html

<!DOCTYPE html>
<html>
<head>
    <title>Education Information</title>
</head>
<body>

    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>
        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1>Education Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>College and University</strong></p>
        <ul>
        {% for education in education_info %}
            <li>{{ education.title }} in {{ education.faculty }} from {{ education.institution_name }}, {{ education.start_date }} - {{ education.end_date }} ({{ education.score }})</li>
            {% endfor %}
        </ul>
    </form>
    {% for education in education_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ education.id }}" > 
            <strong> Delete : {{education.id}}, {{education.title}}  ??</strong>

            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>


resume/templates/generalinformation.html
<!DOCTYPE html>
<html>
<head>
    <title>General Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>
        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>

    <!-- Display personal information form -->
    <h1>General Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <button type="submit">Save</button> -->
        <!-- Display delete button -->
        <input type = "submit" name = "Save" value = "Save">
        <input type = "submit" name="Delete" value = "Delete" >

        
        <!-- <button type="submit" name="Delete">Delete</button> -->
    </form>



</body>
</html>

resume/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hi Vlog!! Welcome to my Channel!!</title>
</head>
<body>
    <p>Welcome to your profile!!
        <a href="{% url 'resume:home' %}">Home</a>
        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>

    </p>  
</body>
<p><strong>Stay Connected with us !! We will have very good updates soon</strong></p>
<div class="container">
    <p>We have got three samples of resume. Please select one to get your desirable one!!</p>
    <!-- <form method="post" action = "{% url 'resume:home' %}"> -->
        <form method="post">
        {% csrf_token %}
        <input type="submit" name="sample" value="First Sample">
        <input type="submit" name="sample" value="Second Sample">
        <input type="submit" name="sample" value="Third Sample">
    </form>
</div>
</html>

resume/templates/job.html
<!DOCTYPE html>
<html>
<head>
    <title>Job Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>
        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1> Job Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>Employment Background</strong></p>
        <ul>
            {% for job in job_info %}
                <li>{{ job.title }} at {{ job.company }} as {{ job.position }} from {{ job.startdate }} - {{ job.enddate }}</li>
            {% endfor %}
        </ul>
    </form>
    {% for job in job_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ job.id }}" > 
            <strong> Delete : {{job.title}} ??</strong>

            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>

resume/templates/language.html
<!DOCTYPE html>
<html>
<head>
    <title>Language Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>
        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1> Language Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>Language</strong></p>
        <ul>
            {% for one in language_info %}
                <li>{{ one.language }}</li>
            {% endfor %}
        </ul>
    </form>
    {% for one in language_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ one.id }}" > 
            <strong> Delete : {{one.language}} ??</strong>

            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>

</html>

resume/templates/login.html
<!-- <!DOCTYPE html>
<html>
<head>
  <title>Login Page</title>
</head>
<body>
  <h1>Login</h1>
  <form action="{% url  'resume:login_user' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>

    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>

    <input type="submit" value="Login">
  </form>

  <p>Don't have an account? <a href="{% url 'resume:register_user' %}">Register here</a>.</p>
</body>
</html> -->


<!DOCTYPE html>
<html>
<head>
  <title>Login Page</title>
</head>
<body>
  <h1>Login</h1>
  <form action="{% url  'resume:login_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Login">
  </form>

  <p>Don't have an account? <a href="{% url 'resume:register_user' %}">Register here</a>.</p>
</body>
</html>

resume/templates/logout.html
<!DOCTYPE html>
<html>
<head>
  <title>Logout Page</title>
</head>
<body>
  <h1>Logout</h1>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'resume:login_user' %}">Login again</a>.</p>
</body>
</html>

resume/templates/project.html
<!DOCTYPE html>
<html>
<head>
    <title>Project Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>

        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1> Project Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>Employment Background</strong></p>
        <ul>
            {% for project in projects %}
                <li>{{ project.title }}: {{ project.description }}</li>
            {% endfor %}
        </ul>
    </form>
    {% for one in project_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ project.id }}" > 
            <strong> Delete : {{one.title}} ??</strong>

            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>

resume/templates/reference.html
<!DOCTYPE html>
<html>
<head>
    <title>Reference Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>

        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1> Reference Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>References</strong></p>
        <ul>
            {% for one in reference_info %}
                <li>{{ one.reference }}</li>
            {% endfor %}
        </ul>
    </form>
    {% for one in reference_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ one.id }}" >
            <strong> Delete : {{one.reference}} ??</strong>
            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>

resume/templates/skill.html
<!DOCTYPE html>
<html>
<head>
    <title>Skill Information</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>

        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <h1> Skill Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="save" value="Save">
        <p><strong>Skills</strong></p>
        <ul>
            {% for one in skill_info %}
                <li>{{ one.skill }}</li>
            {% endfor %}
        </ul>
    </form>
    {% for one in skill_info %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="delete" value="{{ one.id }}" > 
            <strong> Delete : {{one.skill}} ??</strong>


            <input type="submit" value="Delete">
        </form>
    {% endfor %}
</body>
</html>

resume/templates/userdetails.html
<!DOCTYPE html>
<html>
<head>
    <title>General Details</title>
</head>
<body>
    <div class="menu">
        <a href="{% url 'resume:home' %}">Home</a>

        <a href="{% url 'resume:userdetails' %}">User Details</a>
        <a href="{% url 'resume:personalinformation' %}">Personal Information</a>
        <a href="{% url 'resume:education' %}">Education</a>
        <a href="{% url 'resume:job' %}">Job</a>
        <a href="{% url 'resume:project' %}">Project</a>
        <a href="{% url 'resume:skill' %}">Skill</a>
        <a href="{% url 'resume:language' %}">Languages</a>
        <a href="{% url 'resume:reference' %}">References</a>
        <a href="{% url 'resume:displayinformation' %}">Display Infomation</a>
        <a href="{% url 'resume:downloadinpdf' %}">Download In PDF?</a>
        <a href="{% url 'resume:logout_user' %}">Logout Here</a>


    </div>
    <!-- Display personal information form -->
    <h1>User Information</h1>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" name = "Save" value = "Save">

        

    </form>
</body>
</html>